# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.pulsar', 'protobuf-shaded', '2.1.0-incubating')
require_jar('org.apache.pulsar', 'pulsar-client-kafka', '2.3.1')
require_jar('org.apache.pulsar', 'pulsar-client', '2.3.1')
require_jar('org.apache.pulsar', 'pulsar-client-api', '2.3.1')
require_jar('com.github.luben', 'zstd-jni', '1.3.7-3')
require_jar('org.slf4j', 'slf4j-api', '1.7.25')
require_jar('org.lz4', 'lz4-java', '1.5.0')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.7.2')
require_jar('com.sun.activation', 'javax.activation', '1.2.0')
require_jar('javax.validation', 'validation-api', '1.1.0.Final')
require_jar('org.bouncycastle', 'bcpkix-jdk15on', '1.60')
require_jar('org.bouncycastle', 'bcprov-jdk15on', '1.60')
